### ISSUE TITLE
TypeError: unknown: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by yukihirop** [yukihirop/babel-udf-helpers#19]
## Summary

Problems found when running tests in parallel with Jest.

```diff
    const visitor = {
        Program(path) {
            const exportNode = path.get(iExportPath);
            const importPaths = iImportPaths.map((p) => path.get(p));
+          const importBindingRefs = iImportBindingsReferences.map((p) => path.get(p));
            const declar = exportNode.get('declaration');
```

I suspect that this is due to some reason that iImportBindingsReferences contains (or has left) a path that does not exist in the current program body.

`iImportBindingsReferences` when a problem occurs

```js
  console.log
    [
      'body.1.declaration.body.body.1.consequent.argument.callee',
      'body.1.declaration.body.body.5.consequent.argument.callee'
    ]

      at Program (node_modules/babel-udf-helpers/src/builder/plugins/ProgramBuild.ts:45:13)
```

## Details

<details>

```
    TypeError: unknown: Cannot read property 'get' of undefined

      69 |     } = this
      70 |     // @ts-ignore
    > 71 |     const toArrayHelper = traverserThis.addUDFHelper("udf_toArray");
         |                                         ^
      72 |     // @ts-ignore
      73 |     const slicedToArrayHelper = traverserThis.addUDFHelper("udf_slicedToArray")
      74 |

      at NodePath._getPattern (node_modules/@babel/traverse/lib/path/family.js:210:21)
      at NodePath.get (node_modules/@babel/traverse/lib/path/family.js:172:17)
      at node_modules/babel-udf-helpers/src/builder/plugins/ProgramBuild.ts:45:75
          at Array.map (<anonymous>)
      at Program (node_modules/babel-udf-helpers/src/builder/plugins/ProgramBuild.ts:45:59)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:55:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:42:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:90:31)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:84:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:140:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at Object.traverse [as default] (node_modules/@babel/traverse/lib/index.js:66:12)
      at Object.ProgramBuild (node_modules/babel-udf-helpers/src/builder/plugins/ProgramBuild.ts:132:11)
      at Object.build (node_modules/babel-udf-helpers/src/builder/index.ts:68:9)
      at Object.buildProgram (node_modules/babel-udf-helpers/src/builder/index.ts:97:27)
      at File.addUDFHelper (node_modules/babel-udf-helpers/src/core_ext/file.ts:42:38)
      at File.addUDFHelper (node_modules/babel-udf-helpers/src/core_ext/file.ts:39:30)
      at ObjectExpressionTraverser.replaceWith (packages/plugin-transform-destructuring/src/traverser/destructuring/CallExpressionTraverser.ts:71:41)
      at ObjectExpressionTraverser.run (packages/plugin-transform-destructuring/src/traverser/destructuring/CallExpressionTraverser.ts:30:10)
      at PluginPass.CallExpression (packages/plugin-transform-destructuring/src/index.ts:32:34)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:179:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:55:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:42:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:90:31)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:84:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:140:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:97:18)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitMultiple (node_modules/@babel/traverse/lib/context.js:79:17)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:138:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:97:18)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitMultiple (node_modules/@babel/traverse/lib/context.js:79:17)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:138:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:97:18)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:84:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:140:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at traverse (node_modules/@babel/traverse/lib/index.js:66:12)
      at transformFile (node_modules/@babel/core/lib/transformation/index.js:107:29)
          at transformFile.next (<anonymous>)
      at run (node_modules/@babel/core/lib/transformation/index.js:35:12)
          at run.next (<anonymous>)
      at Object.<anonymous> (node_modules/@babel/core/lib/transform-ast.js:28:41)
      at evaluateSync (node_modules/gensync/index.js:244:28)
      at Object.sync (node_modules/gensync/index.js:84:14)
      at Bunlder.createAsset (packages/bundler/src/core/bundler.ts:59:22)
      at Bunlder.createGraph (packages/bundler/src/core/bundler.ts:73:28)
      at Bunlder.<anonymous> (packages/bundler/src/core/bundler.ts:117:24)
      at step (packages/bundler/lib/core/bundler.js:52:23)
      at Object.next (packages/bundler/lib/core/bundler.js:33:53)
      at packages/bundler/lib/core/bundler.js:27:71
      at __awaiter (packages/bundler/lib/core/bundler.js:23:12)
      at Bunlder.write (packages/bundler/lib/core/bundler.js:182:16)
      at packages/plugin-transform-destructuring/__tests__/plugin-transform-destructuring.test.ts:28:42
      at step (packages/plugin-transform-destructuring/__tests__/plugin-transform-destructuring.test.ts:33:23)
      at Object.next (packages/plugin-transform-destructuring/__tests__/plugin-transform-destructuring.test.ts:14:53)
      at packages/plugin-transform-destructuring/__tests__/plugin-transform-destructuring.test.ts:8:71
      at __awaiter (packages/plugin-transform-destructuring/__tests__/plugin-transform-destructuring.test.ts:4:12)
      at build (packages/plugin-transform-destructuring/__tests__/plugin-transform-destructuring.test.ts:65:12)
      at packages/plugin-transform-destructuring/__tests__/plugin-transform-destructuring.test.ts:100:13
      at step (packages/plugin-transform-destructuring/__tests__/plugin-transform-destructuring.test.ts:33:23)
      at Object.next (packages/plugin-transform-destructuring/__tests__/plugin-transform-destructuring.test.ts:14:53)
      at fulfilled (packages/plugin-transform-destructuring/__tests__/plugin-transform-destructuring.test.ts:5:58)
```

</details>

**Comment by yukihirop** [comment]
this is PluginPass instance.

This is the details of this.opts when calling this.addUDFHelper(name)

An error seems to occur when multiple plugins are set

```
      this.opts { babelrc: false,
        configFile: false,
        passPerPreset: false,
        envName: 'test',
        cwd: '/Users/yukihirop/JavaScriptProjects/babel-udf-helpers',
        root: '/Users/yukihirop/JavaScriptProjects/babel-udf-helpers',
        plugins:
         [ Plugin {
             key: 'babel-udf-helpers-test-0',
             manipulateOptions: undefined,
             post: undefined,
             pre: [Function: pre],
             visitor: [Object],
             parserOverride: undefined,
             generatorOverride: undefined,
             options: {} },
           Plugin {
             key: 'babel-udf-helpers-test-1',
             manipulateOptions: undefined,
             post: undefined,
             pre: [Function: pre],
             visitor: [Object],
             parserOverride: undefined,
             generatorOverride: undefined,
             options: {} } ],
        presets: [],
        parserOpts:
         { sourceType: 'module', sourceFileName: undefined, plugins: [] },
        generatorOpts:
         { filename: undefined,
           auxiliaryCommentBefore: undefined,
           auxiliaryCommentAfter: undefined,
           retainLines: undefined,
           comments: true,
           shouldPrintComment: undefined,
           compact: 'auto',
           minified: undefined,
           sourceMaps: false,
           sourceRoot: undefined,
           sourceFileName: 'unknown' } }
```

**Comment by yukihirop** [comment]
```js
describe('addUDFHelper', () => {
  describe('basic', () => {
    const type = 'basic';

    // const dirs = ['declaration', 'dependencies'];
    const dirs = ['dependencies'];

    for (const dir of dirs) {
      test(dir, () => {
        const helpers = require(inputFixturePath([type, dir]));
        // @ts-ignore
        const programFuncs = [(pass) => pass.addUDFHelper(dir)];
        const code = printer({ helpers, programFuncs });

        expect(code).toMatchSnapshot();
        writeFile(outputFixturePath([type, dir]), code || '', () => { });
      });
    }

    // test('rename', () => {
    //   const dir = 'rename';
    //   const helpers = require(inputFixturePath([type, dir]));
    //   const content = `function _rename() { return "path.replaceWith" }`;
    //   const programFuncs = [(pass) => pass.addUDFHelper(dir)];
    //   // @ts-ignore
    //   const code = printer({ content, helpers, programFuncs });

    //   expect(code).toMatchSnapshot();
    //   writeFile(outputFixturePath([type, dir]), code || '', () => { });
    // });

    test('multi plugins', () => {
      const dir = 'dependencies';
      const helpers = require(inputFixturePath([type, dir]));
      const programFuncs = [(pass) => pass.addUDFHelper(dir), (pass) => pass.addUDFHelper(dir)];
      // @ts-ignore
      const code = printer({ helpers, programFuncs });

      expect(code).toMatchSnapshot();
      writeFile(outputFixturePath([type, dir]), code || '', () => { });
    });
  });
});
```

```bash
● addUDFHelper › basic › multi plugins

    TypeError: unknown: Cannot read property 'body' of undefined

      43 |       const exportNode = path.get(iExportPath) as NodePath;
      44 |       const importPaths = iImportPaths.map((p) => path.get(p));
    > 45 |       const importBindingRefs = iImportBindingsReferences.map((p) => path.get(p));
         |                                                                           ^
      46 |
      47 |       const declar = exportNode.get('declaration') as NodePath;
      48 |       if (currentId.type === 'Identifier') {

      at NodePath._getKey (node_modules/@babel/traverse/lib/path/family.js:178:25)
      at NodePath.get (node_modules/@babel/traverse/lib/path/family.js:170:17)
      at NodePath._getPattern (node_modules/@babel/traverse/lib/path/family.js:210:21)
      at NodePath.get (node_modules/@babel/traverse/lib/path/family.js:172:17)
      at Program.iImportBindingsReferences.map (src/builder/plugins/ProgramBuild.ts:45:75)
          at Array.map (<anonymous>)
      at Program (src/builder/plugins/ProgramBuild.ts:45:59)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:55:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:42:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:90:31)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:84:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:140:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at Object.traverse [as default] (node_modules/@babel/traverse/lib/index.js:66:12)
      at Object.ProgramBuild (src/builder/plugins/ProgramBuild.ts:132:11)
      at Object.build (src/builder/index.ts:72:9)
      at Object.buildProgram (src/builder/index.ts:101:27)
      at File.addUDFHelper (src/core_ext/file.ts:44:38)
      at File.addUDFHelper (src/core_ext/file.ts:41:30)
      at programFuncs (src/__tests__/basic.test.ts:50:44)
      at PluginPass.Program (src/__tests__/printer/plugin.ts:22:11)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:179:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:55:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:42:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:90:31)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:84:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:140:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at traverse (node_modules/@babel/traverse/lib/index.js:66:12)
      at transformFile (node_modules/@babel/core/lib/transformation/index.js:107:29)
          at transformFile.next (<anonymous>)
      at run (node_modules/@babel/core/lib/transformation/index.js:35:12)
          at run.next (<anonymous>)
      at Object.<anonymous> (node_modules/@babel/core/lib/transform-ast.js:28:41)
      at evaluateSync (node_modules/gensync/index.js:244:28)
      at Object.sync (node_modules/gensync/index.js:84:14)
      at Object.printer (src/__tests__/printer/index.ts:22:20)
      at Object.test (src/__tests__/basic.test.ts:52:27)
```

**Comment by yukihirop** [comment]
The following cases pass

```js
describe('addUDFHelper', () => {
  describe('basic', () => {
    const type = 'basic';

    // const dirs = ['declaration', 'dependencies'];
    const dirs = ['dependencies'];

    // for (const dir of dirs) {
    //   test(dir, () => {
    //     const helpers = require(inputFixturePath([type, dir]));
    //     // @ts-ignore
    //     const programFuncs = [(pass) => pass.addUDFHelper(dir)];
    //     const code = printer({ helpers, programFuncs });

    //     expect(code).toMatchSnapshot();
    //     writeFile(outputFixturePath([type, dir]), code || '', () => { });
    //   });
    // }

    // test('rename', () => {
    //   const dir = 'rename';
    //   const helpers = require(inputFixturePath([type, dir]));
    //   const content = `function _rename() { return "path.replaceWith" }`;
    //   const programFuncs = [(pass) => pass.addUDFHelper(dir)];
    //   // @ts-ignore
    //   const code = printer({ content, helpers, programFuncs });

    //   expect(code).toMatchSnapshot();
    //   writeFile(outputFixturePath([type, dir]), code || '', () => { });
    // });

    test('multi plugins', () => {
      const dir = 'dependencies';
      const helpers = require(inputFixturePath([type, dir]));
      const programFuncs = [(pass) => pass.addUDFHelper(dir), (pass) => pass.addUDFHelper(dir)];
      // @ts-ignore
      const code = printer({ helpers, programFuncs });

      expect(code).toMatchSnapshot();
      writeFile(outputFixturePath([type, dir]), code || '', () => { });
    });
  });
});
```

**Comment by yukihirop** [comment]
## this.addHelper

`console.log("path.toString", "exportName", Object.create(path).toString(), exportName)`


I can issue the code with `Object.create(path).toString()` 

```js
 FAIL  src/__tests__/basic.test.ts
  ● Console

    console.log
      path.toString exportName export default function _child() {
        return "child1";
      }
      ; _child

      at Program (node_modules/@babel/helpers/lib/index.js:181:15)

    console.log
      path.toString exportName export default function _grandchild() {
        return "grandchild";
      }
      ; _grandchild

      at Program (node_modules/@babel/helpers/lib/index.js:181:15)

    console.log
      path.toString exportName import grandchild from "grandchild";
      export default function _child2() {
        grandchild();
      }
      ; _child2

      at Program (node_modules/@babel/helpers/lib/index.js:181:15)

    console.log
      path.toString exportName import child from "child";
      import child2 from "child2";
      export default function _dependencies() {
        child() || child2();
      }
      ; _dependencies

      at Program (node_modules/@babel/helpers/lib/index.js:181:15)

    console.log
      path.toString exportName export default function _child() {
        return "child1";
      }
      ; _child

      at Program (node_modules/@babel/helpers/lib/index.js:181:15)

    console.log
      path.toString exportName export default function _grandchild() {
        return "grandchild";
      }
      ; _grandchild

      at Program (node_modules/@babel/helpers/lib/index.js:181:15)

    console.log
      path.toString exportName import grandchild from "grandchild";
      export default function _child2() {
        grandchild();
      }
      ; _child2

      at Program (node_modules/@babel/helpers/lib/index.js:181:15)

    console.log
      path.toString exportName import child from "child";
      import child2 from "child2";
      export default function _dependencies() {
        child() || child2();
      }
      ; _dependencies

      at Program (node_modules/@babel/helpers/lib/index.js:181:15)

  ● addUDFHelper › basic › dependencies
```

```
console.log
      path.toString exportName import grandchild from "grandchild";
      export default function _child2() {
        grandchild();
      }
      ; _child2

      at Program (node_modules/@babel/helpers/lib/index.js:181:15)
```

**Comment by yukihirop** [comment]
# Solution


## Before

```ts
        /**
         * Remove helper export default.
         * ・Remove helper import.
         * ・Resolve Referenced Identifier. (rename)
         * ・Global variable traversal (globals)
         * ・Helper code to actually write (nodes)
         */
        execProgramBuildPlugin(builderFile, {
          currentId,
          currentDependencies,
          currentLocalBindingNames,
        });
```

## After

```ts
        /**
         *
         * A new helperBuilder instance needs to be created for each traverse,
         * but only opts needs to be inherited.
         * 
         * https://github.com/babel/babel/blob/c664fbdd07d0a510d5bcb42b4d1776e9354696ad/packages/babel-helpers/src/index.js#L245-L263
         */
        const builderFile = createBuilderFile(helper);
        builderFile.opts = opts;

        /**
         * Remove helper export default.
         * ・Remove helper import.
         * ・Resolve Referenced Identifier. (rename)
         * ・Global variable traversal (globals)
         * ・Helper code to actually write (nodes)
         */
        execProgramBuildPlugin(builderFile, {
          currentId,
          currentDependencies,
          currentLocalBindingNames,
        });
```
